/**
 * @file SMLLoader.cpp
 * @brief SML 文件加载器
 *
 * 从编译器生成的 .sml 文件加载程序到虚拟机。
 * 支持 compiler_2206 生成的扩展指令。
 */

#include "../include/VirtualMachine.h"
#include "../include/ProgramBuilder.h"
#include <fstream>
#include <iostream>
#include <string>
#include <array>

constexpr size_t MEMORY_SIZE = 100;

/**
 * 从 .sml 文件加载程序
 * @param filename SML 文件路径
 * @param memory 目标内存数组
 * @return 成功返回 true
 */
bool loadSMLFile(const std::string& filename, std::array<int, MEMORY_SIZE>& memory) {
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Error: Cannot open file: " << filename << std::endl;
        return false;
    }

    // 初始化内存为 0
    memory.fill(0);

    int address = 0;
    int instruction;
    while (file >> instruction && address < static_cast<int>(MEMORY_SIZE)) {
        memory[address++] = instruction;
    }

    file.close();
    std::cout << "Loaded " << address << " memory cells from " << filename << std::endl;
    return true;
}

/**
 * 主程序：加载并执行 SML 文件
 */
int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cout << "SML Program Loader for vm_2206" << std::endl;
        std::cout << "Usage: " << argv[0] << " <program.sml>" << std::endl;
        std::cout << "\nThis tool loads and executes SML programs generated by" << std::endl;
        std::cout << "the Simple language compiler (compiler_2206)." << std::endl;
        return 1;
    }

    std::string filename = argv[1];

    // 加载程序
    std::array<int, MEMORY_SIZE> program;
    if (!loadSMLFile(filename, program)) {
        return 1;
    }

    // 创建虚拟机并执行
    std::cout << "\n=== Executing " << filename << " ===" << std::endl;
    VirtualMachine vm;
    vm.loadProgram(program);
    vm.execute();

    // 显示执行结果
    std::cout << "\n=== Execution Complete ===" << std::endl;
    vm.dumpRegisters();

    return 0;
}
